"""Geometric layout analysis on top of PDFium.

Pipeline for one page (all coordinates top-left origin, in points):

    chars ──► spans (runs on one baseline, split at wide gaps; super/subscripts kept)
    paths/images ──► rules, ruled tables, figures
    spans + atoms ──► column-aware XY-cut ──► bands in reading order
    bands ──► unruled tables, lines ──► paragraphs, lists, formulas, code

Document-level passes (headings by font size, running headers/footers, captions)
live in `finalize()` so pages can be analysed in parallel processes.

The browser engine (`docs/assets/engine.js`) implements the same algorithm on top
of pdf.js; thresholds are named alike in both files.
"""

from __future__ import annotations

import ctypes
import io
import math
import re
import statistics
from collections import Counter
from dataclasses import dataclass, field

import pypdfium2 as pdfium
import pypdfium2.raw as pr

from .model import FURNITURE, Block, ImageData, Page
from .symbols import (
    BELOW_ACCENTS,
    BULLETS,
    SPACING_ACCENTS,
    compose_accent,
    is_math_font,
    latex_escape,
    math_score,
    normalize_char,
    strip_accents_lower,
    to_subscript,
    to_superscript,
)

# ----------------------------------------------------------------------------- tunables
SPAN_GAP_EM = 0.9  # gap (in font sizes) that splits a line into separate spans
JUSTIFIED_GAP_EM = 2.6  # same, when the PDF has a real space char there (justified text)
WORD_GAP_EM = 0.18  # gap that inserts a space when the PDF has none
PARA_GAP_EM = 0.55  # vertical gap between lines that still belongs to one paragraph
GUTTER_MIN = 5.0  # minimum width of a column gutter, in points
RULE_MAX = 2.5  # max thickness of a path to count as a table rule
EDGE_ZONE = 0.09  # top/bottom share of the page where headers/footers live
TEXT_LIKE_CHARS = 15  # median span length that makes a column "prose" (vs table column)
_PUA_START, _PUA_END = chr(0xE000), chr(0xF8FF)  # glyphs without a real Unicode value

_ENUM = re.compile(
    r"^(\(?(\d{1,3}(\.\d{1,3})*|[a-zA-Z]|[ivxlcdmIVXLCDM]{1,5})[.)]|\(\d{1,3}\)|\([a-z]\))(?=\s|$)"
)
_NUMBERED_HEADING = re.compile(r"^(\d{1,2}(\.\d{1,2}){0,4})\.?\s+\S")
_CAPTION = re.compile(
    r"^(fig(ura|ure)?|tab(ela|le)?|quadro|gr[aá]fico|chart|imagem|image|"
    r"equa[cç][aã]o|equation|listing|algoritmo|algorithm|esquema|diagrama|diagram)"
    r"\.?\s*(\d+(\.\d+)?|[ivxlc]+)\s*([.:\-–—|]|\s|$)",
    re.IGNORECASE,
)
# Without a figure/table next to it, only "Figura 3: ..." / "Tabela 2 - ..." count.
_STRICT_CAPTION = re.compile(
    _CAPTION.pattern.replace(r"([.:\-–—|]|\s|$)", r"[.:\-–—|]"), re.IGNORECASE
)
_KEY_VALUE = re.compile(r"^[^:]{2,40}:\s+\S")
_EQ_NUMBER = re.compile(r"^\(\s*\d{1,3}(\.\d{1,3})?[a-z]?\s*\)$")
_PAGE_NUMBER = re.compile(
    r"^\s*(?:(?:p[áa]g(?:ina)?|page|p)\.?\s*)?[-–—(\[]?\s*(\d{1,4}|[ivxlcdm]{1,6})\s*[-–—)\]]?"
    r"(?:\s*(?:/|de|of)\s*\d{1,4})?\s*$",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class LayoutOptions:
    images: bool = False  # crop figures/tables/formulas to PNG
    image_scale: float = 2.0  # 2.0 = 144 dpi
    table_images: bool = True
    formula_images: bool = True
    detect_tables: bool = True
    detect_formulas: bool = True


# ============================================================================= primitives
@dataclass(slots=True)
class FontInfo:
    name: str
    bold: bool
    italic: bool
    math: bool
    mono: bool
    rotated: bool


@dataclass(slots=True)
class Char:
    c: str
    x0: float
    y0: float
    x1: float
    y1: float
    font: int
    space: int = 0  # space before this char: 0 none, 1 generated by PDFium, 2 real (in the PDF)
    newline: bool = False  # PDFium saw a line break before this char

    @property
    def size(self) -> float:
        return self.y1 - self.y0

    @property
    def cx(self) -> float:
        return (self.x0 + self.x1) / 2

    @property
    def cy(self) -> float:
        return (self.y0 + self.y1) / 2


@dataclass
class Span:
    chars: list[Char]
    fonts: list[FontInfo]
    x0: float = 0
    y0: float = 0
    x1: float = 0
    y1: float = 0
    size: float = 0
    segments: list[tuple[str, str]] = field(default_factory=list)  # ("n"|"sup"|"sub", text)
    bold: bool = False
    italic: bool = False
    math: float = 0.0  # share of chars in a math font
    mono: bool = False

    def __post_init__(self) -> None:
        cs = self.chars
        self.x0 = min(c.x0 for c in cs)
        self.x1 = max(c.x1 for c in cs)
        self.y0 = min(c.y0 for c in cs)
        self.y1 = max(c.y1 for c in cs)
        self.size = _mode_size(cs)
        fonts = [self.fonts[c.font] for c in cs]
        n = len(fonts)
        self.bold = sum(f.bold for f in fonts) > n * 0.6
        self.italic = sum(f.italic for f in fonts) > n * 0.6
        self.mono = sum(f.mono for f in fonts) > n * 0.8
        self.math = sum(f.math for f in fonts) / n
        self.segments = _segments(cs, self.size)

    @property
    def text(self) -> str:
        return segments_text(self.segments)

    @property
    def width(self) -> float:
        return self.x1 - self.x0

    @property
    def height(self) -> float:
        return self.y1 - self.y0


def _mode_size(chars: list[Char]) -> float:
    """Most common glyph size (to the half point)."""
    counts: dict[float, int] = {}
    for c in chars:
        k = round(c.size * 2) / 2
        counts[k] = counts.get(k, 0) + 1
    return max(counts, key=counts.__getitem__)


def _segments(chars: list[Char], main: float) -> list[tuple[str, str]]:
    """Text of one line, with superscript / subscript runs marked by baseline shift."""
    normal = [c.y1 for c in chars if abs(c.size - main) <= main * 0.12] or [c.y1 for c in chars]
    base = statistics.median(normal)
    # Letter-spaced text ("T Í T U L O") has wide gaps between every glyph: a word gap
    # must be wide *relative to the usual gap of this run*, not just in absolute terms.
    gaps = [b.x0 - a.x1 for a, b in zip(chars, chars[1:], strict=False) if b.space < 2]
    tracking = max(0.0, statistics.median(gaps)) if len(gaps) >= 3 else 0.0
    word_gap = tracking + max(main, 1) * WORD_GAP_EM
    out: list[list[str]] = []
    prev: Char | None = None
    for ch in chars:
        kind = "n"
        if ch.size < main * 0.86:
            if base - ch.y1 > main * 0.2:
                kind = "sup"
            elif ch.y1 - base > main * 0.08:
                kind = "sub"
        gap = ch.x0 - prev.x1 if prev else 0
        space = prev is not None and (
            ch.space == 2 or gap > word_gap or (ch.space and gap > word_gap * 0.6)
        )
        if out and out[-1][0] == kind:
            out[-1][1] += (" " if space else "") + ch.c
        else:
            if space and out:
                out[-1][1] += " "
            out.append([kind, ch.c])
        prev = ch
    return [(k, t) for k, t in out]


def segments_text(segments: list[tuple[str, str]]) -> str:
    parts = []
    for kind, text in segments:
        if kind == "n":
            parts.append(text)
            continue
        conv = to_superscript(text) if kind == "sup" else to_subscript(text)
        if conv is not None:
            parts.append(conv)
        else:
            mark = "^" if kind == "sup" else "_"
            t = text.strip()
            parts.append(f"{mark}{t}" if len(t) == 1 else f"{mark}({t})")
    return "".join(parts)


def segments_latex(segments: list[tuple[str, str]]) -> str:
    parts = []
    for kind, text in segments:
        body = latex_escape(text.strip() if kind != "n" else text)
        parts.append(body if kind == "n" else ("^{" if kind == "sup" else "_{") + body + "}")
    return re.sub(r"\s+", " ", "".join(parts)).strip()


# ============================================================================= PDFium readers
def _font_info(obj) -> FontInfo:
    name, weight, flags = "", -1, 0
    font = pr.FPDFTextObj_GetFont(obj) if obj else None
    if font:
        size = pr.FPDFFont_GetBaseFontName(font, None, 0)
        if size > 0:
            buf = ctypes.create_string_buffer(size)
            pr.FPDFFont_GetBaseFontName(font, buf, size)
            name = buf.value.decode("utf-8", "replace")
        weight = pr.FPDFFont_GetWeight(font)
        flags = pr.FPDFFont_GetFlags(font)
    low = name.lower().split("+")[-1]  # drop subset prefix "ABCDEF+"
    rotated = False
    if obj:
        m = pr.FS_MATRIX()
        if pr.FPDFPageObj_GetMatrix(obj, ctypes.byref(m)):
            rotated = abs(m.b) > abs(m.a) * 0.2 or abs(m.c) > abs(m.d) * 0.2
    return FontInfo(
        name=name,
        bold=weight >= 600 or any(k in low for k in ("bold", "black", "heavy", "semibold", "demi")),
        italic=bool(flags & 64) or "italic" in low or "oblique" in low,
        math=is_math_font(low),
        mono=bool(flags & 1)
        or any(k in low for k in ("mono", "courier", "consol", "menlo", "inconsolata")),
        rotated=rotated,
    )


def _fast(fn, restype, *argtypes):
    """Re-declare a hot PDFium function with plain C types.

    pypdfium2's bindings take typed pointers; converting them costs more than the call
    itself when done once per glyph. Same symbol, same library — just cheaper marshalling.
    """
    addr = ctypes.cast(fn, ctypes.c_void_p).value
    return ctypes.CFUNCTYPE(restype, *argtypes)(addr)


_VP, _INT = ctypes.c_void_p, ctypes.c_int
_get_unicode = _fast(pr.FPDFText_GetUnicode, ctypes.c_uint, _VP, _INT)
_get_textobj = _fast(pr.FPDFText_GetTextObject, _VP, _VP, _INT)
_get_loose_box = _fast(pr.FPDFText_GetLooseCharBox, _INT, _VP, _INT, _VP)
_is_generated = _fast(pr.FPDFText_IsGenerated, _INT, _VP, _INT)
_HYPHEN_MARKS = (2, 0xFFFE)  # PDFium's marker for an end-of-line hyphenation


def read_chars(page: pdfium.PdfPage, crop: tuple[float, float, float, float]):
    """Every visible glyph with its loose box, font, and space/line-break hints."""
    textpage = page.get_textpage()
    tp = ctypes.cast(textpage.raw, _VP).value
    left, _, _, top = crop
    n = pr.FPDFText_CountChars(textpage.raw)
    rect = pr.FS_RECTF()
    rect_ptr = ctypes.addressof(rect)
    fonts: list[FontInfo] = []
    font_index: dict[int, int] = {}
    chars: list[Char] = []
    rotated: list[Char] = []
    space, newline = 0, False
    map_errors = 0
    for i in range(n):
        u = _get_unicode(tp, i)
        if u in (10, 13):
            newline = True
            continue
        if u in (32, 9, 0):
            space = max(space, 1 if _is_generated(tp, i) else 2)
            continue
        key = _get_textobj(tp, i) or 0
        fi = font_index.get(key)
        if fi is None:
            fi = font_index[key] = len(fonts)
            fonts.append(_font_info(ctypes.cast(key, pr.FPDF_PAGEOBJECT) if key else None))
        c = "-" if u in _HYPHEN_MARKS else normalize_char(chr(u), fonts[fi].name)
        if not c or c.isspace():
            space = max(space, 2) if c.isspace() else space
            continue
        if not _get_loose_box(tp, i, rect_ptr):
            continue
        if _PUA_START <= c[0] <= _PUA_END:
            map_errors += 1
        ch = Char(
            c,
            rect.left - left,
            top - rect.top,
            rect.right - left,
            top - rect.bottom,
            fi,
            space,
            newline,
        )
        if ch.y1 - ch.y0 <= 0.1:
            continue
        (rotated if fonts[fi].rotated else chars).append(ch)
        space, newline = 0, False
    textpage.close()
    return chars, rotated, fonts, map_errors


def _matrix(obj) -> tuple[float, ...]:
    m = pr.FS_MATRIX()
    if pr.FPDFPageObj_GetMatrix(obj, ctypes.byref(m)):
        return (m.a, m.b, m.c, m.d, m.e, m.f)
    return (1, 0, 0, 1, 0, 0)


def _mul(m, n):
    """m then n (row-vector convention, like PDF)."""
    a, b, c, d, e, f = m
    A, B, C, D, E, F = n
    return (
        a * A + b * C,
        a * B + b * D,
        c * A + d * C,
        c * B + d * D,
        e * A + f * C + E,
        e * B + f * D + F,
    )


def _apply(m, x, y):
    a, b, c, d, e, f = m
    return a * x + c * y + e, b * x + d * y + f


@dataclass
class Graphics:
    hrules: list[tuple[float, float, float]] = field(default_factory=list)  # (y, x0, x1)
    vrules: list[tuple[float, float, float]] = field(default_factory=list)  # (x, y0, y1)
    ink: list[tuple[float, float, float, float]] = field(default_factory=list)  # vector art boxes
    images: list[tuple[float, float, float, float]] = field(default_factory=list)


def read_graphics(page: pdfium.PdfPage, crop, width: float, height: float) -> Graphics:
    g = Graphics()
    left, _, _, top = crop
    page_area = width * height
    identity = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
    L, B, R, T = (ctypes.c_float() for _ in range(4))
    fx, fy = ctypes.c_float(), ctypes.c_float()
    fx_ref, fy_ref = ctypes.byref(fx), ctypes.byref(fy)

    def to_page(m, x0, y0, x1, y1):
        pts = [_apply(m, x, y) for x, y in ((x0, y0), (x1, y0), (x0, y1), (x1, y1))]
        xs = [p[0] - left for p in pts]
        ys = [top - p[1] for p in pts]
        return min(xs), min(ys), max(xs), max(ys)

    def add_box_rules(x0, y0, x1, y1):
        w, h = x1 - x0, y1 - y0
        if w <= RULE_MAX and h > 3:
            g.vrules.append(((x0 + x1) / 2, y0, y1))
        elif h <= RULE_MAX and w > 3:
            g.hrules.append(((y0 + y1) / 2, x0, x1))
        elif w * h < page_area * 0.6:
            g.hrules += [(y0, x0, x1), (y1, x0, x1)]
            g.vrules += [(x0, y0, y1), (x1, y0, y1)]

    def path(obj, form_m):
        if not pr.FPDFPageObj_GetBounds(obj, *(ctypes.byref(v) for v in (L, B, R, T))):
            return
        box = to_page(form_m, L.value, B.value, R.value, T.value)
        x0, y0, x1, y1 = box
        if x1 < -5 or y1 < -5 or x0 > width + 5 or y0 > height + 5:
            return  # off-page
        fill, stroke = ctypes.c_int(), ctypes.c_int()
        pr.FPDFPath_GetDrawMode(obj, ctypes.byref(fill), ctypes.byref(stroke))
        if not fill.value and not stroke.value:
            return  # clipping path / invisible
        if fill.value and not stroke.value:
            r, gg, b, a = (ctypes.c_uint() for _ in range(4))
            pr.FPDFPageObj_GetFillColor(obj, *(ctypes.byref(v) for v in (r, gg, b, a)))
            if a.value == 0 or min(r.value, gg.value, b.value) >= 250:
                return  # white / transparent fill: masking, not ink
        nseg = pr.FPDFPath_CountSegments(obj)
        w, h = x1 - x0, y1 - y0
        if w <= RULE_MAX or h <= RULE_MAX or nseg <= 6:
            add_box_rules(x0, y0, x1, y1)
            return
        # Many segments: either a grid drawn as one path, or vector art. Small or huge
        # paths can't be table grids — don't pay for decoding their segments.
        if w < 30 or h < 12 or nseg > 800:
            if w * h < page_area * 0.9:
                g.ink.append(box)
            return
        m = _mul(_matrix(obj), form_m)
        straight = curves = 0
        pts: list[tuple[float, float, int]] = []
        for s in range(nseg):
            seg = pr.FPDFPath_GetPathSegment(obj, s)
            kind = pr.FPDFPathSegment_GetType(seg)
            if kind == pr.FPDF_SEGMENT_BEZIERTO:
                curves += 1
                if curves > 4:
                    break  # curves: vector art, not a grid
            pr.FPDFPathSegment_GetPoint(seg, fx_ref, fy_ref)
            px, py = _apply(m, fx.value, fy.value)
            pts.append((px - left, top - py, kind))
        segs = []
        for (ax, ay, _), (bx, by, kind) in zip(pts, pts[1:], strict=False):
            if kind != pr.FPDF_SEGMENT_LINETO:
                continue
            if abs(ay - by) <= 0.5 and abs(ax - bx) > 3:
                segs.append(("h", (ay + by) / 2, min(ax, bx), max(ax, bx)))
                straight += 1
            elif abs(ax - bx) <= 0.5 and abs(ay - by) > 3:
                segs.append(("v", (ax + bx) / 2, min(ay, by), max(ay, by)))
                straight += 1
        if curves == 0 and straight >= len(pts) * 0.6:
            for kind, pos, a, b in segs:
                (g.hrules if kind == "h" else g.vrules).append((pos, a, b))
        elif w * h < page_area * 0.9:
            g.ink.append(box)

    def walk(parent, form_m, is_form):
        count = pr.FPDFFormObj_CountObjects(parent) if is_form else pr.FPDFPage_CountObjects(parent)
        for i in range(count):
            obj = (
                pr.FPDFFormObj_GetObject(parent, i) if is_form else pr.FPDFPage_GetObject(parent, i)
            )
            kind = pr.FPDFPageObj_GetType(obj)
            if kind == pr.FPDF_PAGEOBJ_PATH:
                path(obj, form_m)
            elif kind == pr.FPDF_PAGEOBJ_IMAGE:
                if pr.FPDFPageObj_GetBounds(obj, *(ctypes.byref(v) for v in (L, B, R, T))):
                    box = to_page(form_m, L.value, B.value, R.value, T.value)
                    if box[2] - box[0] >= 8 and box[3] - box[1] >= 8:
                        g.images.append(box)
            elif kind == pr.FPDF_PAGEOBJ_SHADING:
                if pr.FPDFPageObj_GetBounds(obj, *(ctypes.byref(v) for v in (L, B, R, T))):
                    box = to_page(form_m, L.value, B.value, R.value, T.value)
                    if (box[2] - box[0]) * (box[3] - box[1]) < page_area * 0.9:
                        g.ink.append(box)
            elif kind == pr.FPDF_PAGEOBJ_FORM:
                walk(obj, _mul(_matrix(obj), form_m), True)

    walk(page.raw, identity, False)
    return g


# ============================================================================= spans
def build_spans(chars: list[Char], fonts: list[FontInfo]) -> list[Span]:
    """Group chars into visual lines (stream order + geometry), then split at wide gaps."""
    raw_lines: list[list[Char]] = []
    cur: list[Char] = []
    for ch in chars:
        if cur:
            last = cur[-1]
            overlap = min(last.y1, ch.y1) - max(last.y0, ch.y0)
            small = min(last.size, ch.size)
            same_line = overlap >= small * 0.35 and ch.x0 >= last.x0 - small * 0.5
            if not same_line or (ch.newline and not overlap >= small * 0.8):
                raw_lines.append(cur)
                cur = []
        cur.append(ch)
    if cur:
        raw_lines.append(cur)

    raw_lines = _merge_fragments(raw_lines)
    spans: list[Span] = []
    for line in raw_lines:
        line.sort(key=lambda c: c.x0)
        line = _compose_accents(line)
        size = max(statistics.median(c.size for c in line), 4)
        # Justified lines stretch every word gap by about the same amount, so a gap only
        # separates columns/cells when it is much wider than this line's usual word gap.
        pairs = list(zip(line, line[1:], strict=False))
        word_gaps = [b.x0 - a.x1 for a, b in pairs if b.space or b.x0 - a.x1 > size * WORD_GAP_EM]
        typical = statistics.median(word_gaps) if len(word_gaps) >= 3 else 0.0
        piece = [line[0]]
        for prev, ch in pairs:
            gap = ch.x0 - prev.x1
            wide = gap > size * SPAN_GAP_EM and (
                gap > typical * 2.2 or gap > size * JUSTIFIED_GAP_EM
            )
            if ch.space == 2 and gap < size * JUSTIFIED_GAP_EM:
                wide = False  # a real space char means "same text run"
            if wide:
                spans.append(Span(piece, fonts))
                piece = []
            piece.append(ch)
        spans.append(Span(piece, fonts))
    return _join_markers(spans)


def _compose_accents(line: list[Char]) -> list[Char]:
    """Merge accents drawn as separate glyphs into their letter ('a' + '˜' -> 'ã').

    The letter is the neighbour the accent overlaps horizontally; without overlap, accents
    drawn above attach to the previous letter and cedillas/ogoneks to the next one.
    """
    if not any(c.c in SPACING_ACCENTS for c in line):
        return line
    out = list(line)
    i = 0
    while i < len(out):
        acc = out[i]
        if acc.c not in SPACING_ACCENTS:
            i += 1
            continue
        best, best_score = None, 0.0
        for j in (i - 1, i + 1):
            if not 0 <= j < len(out) or compose_accent(out[j].c, acc.c) is None:
                continue
            base = out[j]
            overlap = min(base.x1, acc.x1 + 0.5) - max(base.x0, acc.x0 - 0.5)
            near = max(base.x0 - acc.x1, acc.x0 - base.x1) < max(acc.size, 4) * 0.3
            prefer = (j > i) == (SPACING_ACCENTS[acc.c] in BELOW_ACCENTS)
            score = overlap if overlap > 0 else (0.5 if near and prefer else 0.0)
            if score > best_score:
                best, best_score = j, score
        if best is None:
            i += 1
            continue
        base = out[best]
        base.c = compose_accent(base.c, acc.c)
        base.space = max(base.space, acc.space) if best > i else base.space
        del out[i]
        # Drawing the accent moves the pen back: a fake space can follow the composed letter.
        k = out.index(base) + 1
        if k < len(out) and out[k].x0 - base.x1 < max(out[k].size, 4) * 0.15:
            out[k].space = 0
    return out


def _merge_fragments(lines: list[list[Char]]) -> list[list[Char]]:
    """Fragments of one visual line drawn at different moments of the stream."""
    if len(lines) < 2:
        return lines
    boxes = [
        [min(c.x0 for c in ln), min(c.y0 for c in ln), max(c.x1 for c in ln), max(c.y1 for c in ln)]
        for ln in lines
    ]
    order = sorted(range(len(lines)), key=lambda i: (boxes[i][1], boxes[i][0]))
    merged: list[int] = []
    out: dict[int, list[Char]] = {}
    for i in order:
        bi = boxes[i]
        target = None
        for j in merged[-6:]:
            bj = boxes[j]
            hi, hj = bi[3] - bi[1], bj[3] - bj[1]
            h = min(hi, hj)
            overlap = min(bi[3], bj[3]) - max(bi[1], bj[1])
            touching = bi[0] <= bj[2] + h * SPAN_GAP_EM and bj[0] <= bi[2] + h * SPAN_GAP_EM
            if overlap >= h * 0.7 and touching:
                target = j
                break
            # A superscript/subscript drawn on its own: smaller, partly overlapping, and
            # glued to the end (or start) of the bigger fragment.
            glued = bi[0] <= bj[2] + h * 0.4 and bj[0] <= bi[2] + h * 0.4
            if h <= max(hi, hj) * 0.8 and overlap >= h * 0.2 and glued:
                target = j
                break
        if target is None:
            merged.append(i)
            out[i] = list(lines[i])
        else:
            out[target].extend(lines[i])
            bj = boxes[target]
            boxes[target] = [
                min(bj[0], bi[0]),
                min(bj[1], bi[1]),
                max(bj[2], bi[2]),
                max(bj[3], bi[3]),
            ]
    return [out[i] for i in merged]


def _is_marker(text: str) -> bool:
    t = text.strip()
    return (len(t) == 1 and t in BULLETS) or bool(_ENUM.fullmatch(t))


def _join_markers(spans: list[Span]) -> list[Span]:
    """'•' or '1.' followed by the item text (hanging indent) is one span, not two columns."""
    out: list[Span] = []
    i = 0
    while i < len(spans):
        s = spans[i]
        if i + 1 < len(spans) and _is_marker(s.text):
            nxt = spans[i + 1]
            same_row = min(s.y1, nxt.y1) - max(s.y0, nxt.y0) > min(s.height, nxt.height) * 0.4
            if same_row and 0 <= nxt.x0 - s.x1 < max(s.size, 6) * 4:
                nxt.chars[0].space = 2
                out.append(Span(s.chars + nxt.chars, s.fonts))
                i += 2
                continue
        out.append(s)
        i += 1
    return out


# ============================================================================ atoms, reading order
@dataclass
class Atom:
    kind: str  # "span" | "table" | "figure"
    x0: float
    y0: float
    x1: float
    y1: float
    span: Span | None = None
    block: Block | None = None

    @property
    def core(self) -> tuple[float, float]:
        if self.kind != "span":
            return self.y0, self.y1
        pad = (self.y1 - self.y0) * 0.22
        return self.y0 + pad, self.y1 - pad


def _bands(items: list[Atom]) -> list[list[Atom]]:
    items = sorted(items, key=lambda a: a.core[0])
    bands: list[list[Atom]] = []
    bottom = -math.inf
    for a in items:
        top, bot = a.core
        if bands and top < bottom:
            bands[-1].append(a)
            bottom = max(bottom, bot)
        else:
            bands.append([a])
            bottom = bot
    return bands


def _gutters(items: list[Atom], min_gap: float) -> list[tuple[float, float]]:
    spans = sorted((a.x0, a.x1) for a in items)
    gaps = []
    end = spans[0][1]
    for x0, x1 in spans[1:]:
        if x0 - end >= min_gap:
            gaps.append((end, x0))
        end = max(end, x1)
    return gaps


def _text_like(side: list[Atom]) -> bool:
    if any(a.kind != "span" for a in side):
        return True
    lengths = [len(a.span.text) for a in side if a.span]
    return bool(lengths) and statistics.median(lengths) >= TEXT_LIKE_CHARS


def _split_columns(items: list[Atom], min_gap: float) -> list[list[Atom]] | None:
    if len(items) < 2:
        return None
    cols: list[list[Atom]] = []
    rest = items
    gutters = _gutters(items, min_gap)
    rows = [b for b in _bands(items) if _table_row(b)] if gutters else []
    for g0, g1 in gutters:
        left = [a for a in rest if a.x1 <= g0 + 0.01]
        right = [a for a in rest if a.x0 >= g1 - 0.01]
        cuts_table = any(
            any(a.x1 <= g0 + 0.01 for a in row) and any(a.x0 >= g1 - 0.01 for a in row)
            for row in rows
        )
        if left and right and not cuts_table and _text_like(left) and _text_like(right):
            cols.append(left)
            rest = right
    if not cols:
        return None
    cols.append(rest)
    return cols


def _table_row(band: list[Atom]) -> bool:
    """Several short cells side by side (a table row), rather than lines of prose columns."""
    spans = [a.span for a in band if a.kind == "span" and a.span]
    return (
        len(spans) >= 3
        and len(spans) == len(band)
        and all(len(s.text) < TEXT_LIKE_CHARS for s in spans)
    )


def reading_order(items: list[Atom], min_gap: float) -> list[list[Atom]]:
    """Column-aware recursive XY-cut. Returns bands (atoms on one visual row) in order."""
    if not items:
        return []
    if len(items) == 1:
        return [items]
    cols = _split_columns(items, min_gap)
    if cols:
        return [band for col in cols for band in reading_order(col, min_gap)]
    bands = _bands(items)
    if len(bands) == 1:
        return [sorted(items, key=lambda a: a.x0)]
    groups: list[list[Atom]] = [bands[0]]
    for band in bands[1:]:
        union = groups[-1] + band
        if _table_row(band) and not _table_row(groups[-1][-1:]):
            groups.append(band)  # a table starts under the columns: don't let a gutter cut it
        elif _split_columns(union, min_gap):
            groups[-1] = union
        else:
            groups.append(band)
    out: list[list[Atom]] = []
    for group in groups:
        if len(group) == len(items):  # no progress possible: stop here
            out += [sorted(b, key=lambda a: a.x0) for b in _bands(group)]
        else:
            out += reading_order(group, min_gap)
    return out


# ============================================================================= tables
def _cluster(values: list[float], tol: float) -> list[float]:
    out: list[list[float]] = []
    for v in sorted(values):
        if out and v - out[-1][-1] <= tol:
            out[-1].append(v)
        else:
            out.append([v])
    return [sum(c) / len(c) for c in out]


def _merge_rules(rules: list[tuple[float, float, float]]) -> list[list[float]]:
    rules = sorted(rules)
    out: list[list[float]] = []
    for pos, a, b in rules:
        for r in out[-8:]:
            if abs(r[0] - pos) <= 1.5 and a <= r[2] + 2 and b >= r[1] - 2:
                r[1], r[2] = min(r[1], a), max(r[2], b)
                break
        else:
            out.append([pos, a, b])
    return out


def _prose_between(spans, x0: float, x1: float, ya: float, yb: float) -> bool:
    """Is there running text (not table rows) between two horizontal rules?"""
    for s in spans:
        cx, cy = (s.x0 + s.x1) / 2, (s.y0 + s.y1) / 2
        if x0 <= cx <= x1 and ya < cy < yb:
            words = [w for w in s.text.split() if len(w) >= 2 and w[0].isalpha()]
            if len(words) >= 7:
                return True
    return False


def ruled_regions(
    g: Graphics, spans=()
) -> list[tuple[tuple[float, float, float, float], list[float], list[float], bool]]:
    """Connected grids of rules -> (bbox, column x's, row y's, has real vertical rules)."""
    H = _merge_rules(g.hrules)
    V = _merge_rules(g.vrules)
    n = len(H) + len(V)
    if len(H) < 2:
        return []
    parent = list(range(n))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    tol = 2.5
    for i, (hy, hx0, hx1) in enumerate(H):
        for j, (vx, vy0, vy1) in enumerate(V):
            if hx0 - tol <= vx <= hx1 + tol and vy0 - tol <= hy <= vy1 + tol:
                parent[find(i)] = find(len(H) + j)
    # Stacked horizontal rules of similar extent with no verticals (booktabs, Word "rows
    # only") — unless running text sits between them: a page-header rule and a table further
    # down share the page width, but the paragraphs in between are not table cells.
    # Rules already tied to vertical rules belong to a full grid: two Word tables of the same
    # width, one below the other, are two tables.
    gridded = {find(len(H) + j) for j in range(len(V))}
    for i in range(len(H)):
        for j in range(i + 1, len(H)):
            a, b = H[i], H[j]
            if find(i) in gridded or find(j) in gridded:
                continue
            if abs(a[1] - b[1]) <= 4 and abs(a[2] - b[2]) <= 4 and a[2] - a[1] > 30:
                lo, hi = sorted((a[0], b[0]))
                image_between = any(im[1] < hi and im[3] > lo for im in g.images)
                if not image_between and not _prose_between(spans, a[1], a[2], lo, hi):
                    parent[find(i)] = find(j)
    comps: dict[int, list[int]] = {}
    for i in range(n):
        comps.setdefault(find(i), []).append(i)
    out = []
    for members in comps.values():
        hs = [H[i] for i in members if i < len(H)]
        vs = [V[i - len(H)] for i in members if i >= len(H)]
        if len(hs) < 2:
            continue
        x0 = min([h[1] for h in hs] + [v[0] for v in vs])
        x1 = max([h[2] for h in hs] + [v[0] for v in vs])
        y0 = min([h[0] for h in hs] + [v[1] for v in vs])
        y1 = max([h[0] for h in hs] + [v[2] for v in vs])
        if x1 - x0 < 30 or y1 - y0 < 8:
            continue
        xs = _cluster([v[0] for v in vs] + [x0, x1], 3)
        ys = _cluster([h[0] for h in hs] + [y0, y1], 2)
        out.append(((x0, y0, x1, y1), xs, ys, len(xs) >= 3))
    return out


def _chars_text(chars: list[Char]) -> str:
    """Multi-line text of a set of chars (cell contents, figure labels)."""
    if not chars:
        return ""
    chars = sorted(chars, key=lambda c: (c.cy, c.x0))
    lines: list[list[Char]] = [[chars[0]]]
    for ch in chars[1:]:
        last = lines[-1]
        ref = statistics.median(c.cy for c in last)
        if abs(ch.cy - ref) <= max(ch.size, last[0].size) * 0.45:
            last.append(ch)
        else:
            lines.append([ch])
    out = []
    for ln in lines:
        ln.sort(key=lambda c: c.x0)
        out.append(segments_text(_segments(ln, _mode_size(ln))))
    return "\n".join(t.strip() for t in out if t.strip())


@dataclass
class Word:
    """A run of glyphs with no space inside: the unit that goes into a table cell, so a
    column boundary can never cut "0,014" or "Brasília" in two."""

    chars: list[Char]

    @property
    def x0(self) -> float:
        return self.chars[0].x0

    @property
    def x1(self) -> float:
        return max(c.x1 for c in self.chars)

    @property
    def cx(self) -> float:
        return (self.x0 + self.x1) / 2

    @property
    def cy(self) -> float:
        return statistics.median(c.cy for c in self.chars)


def words_of(span: Span) -> list[Word]:
    size = max(span.size, 4)
    words: list[Word] = []
    cur = [span.chars[0]]
    for prev, ch in zip(span.chars, span.chars[1:], strict=False):
        gap = ch.x0 - prev.x1
        if ch.space == 2 or gap > size * 0.25 or (ch.space and gap > size * 0.1):
            words.append(Word(cur))
            cur = []
        cur.append(ch)
    words.append(Word(cur))
    return words


def _projection_columns(spans: list[Span], x0: float, x1: float) -> list[float]:
    """Column boundaries: vertical whitespace channels that no word crosses.

    Rows with far fewer words than usual (a title spanning several columns, a
    "Fase 1 - Iniciação" divider) are left out of the projection: they would cover the
    channels of the columns below them.
    """
    atoms = [Atom("span", s.x0, s.y0, s.x1, s.y1, span=s) for s in spans]
    bands = [[w for a in band for w in words_of(a.span)] for band in _bands(atoms)]
    counts = [len(b) for b in bands]
    typical = statistics.median(counts)
    body = [b for b, n in zip(bands, counts, strict=True) if n >= typical * 0.5 and n >= 2]
    words = [w for b in (body if len(body) >= 2 else bands) for w in b]
    size = statistics.median(s.size for s in spans)
    min_gap = max(3.0, size * 0.55)
    ivs = sorted((w.x0, w.x1) for w in words)
    bounds = [x0]
    end = ivs[0][1]
    for a, b in ivs[1:]:
        if a - end >= min_gap:
            bounds.append((a + end) / 2)
        end = max(end, b)
    bounds.append(x1)
    return bounds


def _grid_rows(words: list[Word], xs: list[float], ys: list[float]) -> list[list[str]]:
    ncol, nrow = len(xs) - 1, len(ys) - 1
    cells: list[list[list[Char]]] = [[[] for _ in range(ncol)] for _ in range(nrow)]
    for w in words:
        r = _bucket(w.cy, ys)
        c = _bucket(w.cx, xs)
        if r is not None and c is not None:
            cells[r][c].extend(w.chars)
    rows = [[_chars_text(cell) for cell in row] for row in cells]
    rows = [row for row in rows if any(row)]
    if rows:
        keep = [j for j in range(ncol) if any(row[j] for row in rows)]
        rows = [[row[j] for j in keep] for row in rows]
    return rows


def _bucket(v: float, edges: list[float]) -> int | None:
    if v < edges[0] - 1 or v > edges[-1] + 1:
        return None
    for i in range(len(edges) - 1):
        if v <= edges[i + 1]:
            return i
    return len(edges) - 2


def _table_block(bbox, rows: list[list[str]]) -> Block | None:
    if len(rows) < 2 or max(len(r) for r in rows) < 2:
        return None
    filled = sum(1 for r in rows for c in r if c)
    if filled < 3:
        return None
    text = "\n".join(" | ".join(c.replace("\n", " ") for c in r) for r in rows)
    return Block("table", tuple(bbox), text=text, rows=rows)


def _band_rows(spans: list[Span]) -> list[float]:
    """Row boundaries from text bands (used when rules don't separate rows)."""
    atoms = [Atom("span", s.x0, s.y0, s.x1, s.y1, span=s) for s in spans]
    bands = _bands(atoms)
    edges = [min(a.y0 for a in bands[0])]
    for prev, nxt in zip(bands, bands[1:], strict=False):
        edges.append((max(a.y1 for a in prev) + min(a.y0 for a in nxt)) / 2)
    edges.append(max(a.y1 for a in bands[-1]))
    return edges


def detect_ruled_tables(spans: list[Span], g: Graphics) -> tuple[list[Block], list[Span]]:
    tables: list[Block] = []
    used: set[int] = set()
    for bbox, xs, ys, real_v in ruled_regions(g, spans):
        x0, y0, x1, y1 = bbox
        inside = [
            i for i, s in enumerate(spans)
            if i not in used
            and x0 - 2 <= (s.x0 + s.x1) / 2 <= x1 + 2
            and y0 - 2 <= (s.y0 + s.y1) / 2 <= y1 + 2
        ]  # fmt: skip
        if not inside:
            continue
        ins = [spans[i] for i in inside]
        if not real_v:  # rows only: take columns from text alignment
            xs = _projection_columns(ins, x0, x1)
        # Rows: trust the rules of a full grid (a cell may wrap over several lines). Split
        # by text bands when rules only frame the table (booktabs: top/mid/bottom), or when
        # a rule row holds several lines with cells in several columns.
        if not real_v and (len(ys) <= 4 or _looks_unruled_rows(ins, ys)):
            bands = _band_rows(ins)
            if len(bands) > len(ys):
                ys = sorted(set(_cluster(ys + bands, 2)))
        words = [w for s in ins for w in words_of(s)]
        block = _table_block(bbox, _grid_rows(words, xs, ys))
        if block is None:
            continue
        tables.append(block)
        used.update(inside)
    return tables, [s for i, s in enumerate(spans) if i not in used]


def _looks_unruled_rows(spans: list[Span], ys: list[float]) -> bool:
    """A rule row holding 3+ text lines that each have 2+ cells is several rows."""
    for a, b in zip(ys, ys[1:], strict=False):
        inside = [s for s in spans if a <= (s.y0 + s.y1) / 2 <= b]
        bands = _bands([Atom("span", s.x0, s.y0, s.x1, s.y1, span=s) for s in inside])
        if len(bands) >= 3 and sum(1 for band in bands if len(band) >= 2) >= 3:
            return True
    return False


def unruled_table(bands: list[list[Atom]], start: int, body: float) -> tuple[Block | None, int]:
    """Try to grow a table from bands[start]; return (table, index after it)."""
    first = bands[start]
    if len(first) < 2 or any(a.kind != "span" for a in first):
        return None, start
    run = [first]
    singles = 0
    j = start + 1
    while j < len(bands):
        band = bands[j]
        if any(a.kind != "span" for a in band):
            break
        prev_bottom = max(a.y1 for a in run[-1])
        top = min(a.y0 for a in band)
        if top - prev_bottom > body * 1.6:
            break
        spans = [a.span for b in run + [band] for a in b]
        rx0 = min(s.x0 for s in spans)
        rx1 = max(s.x1 for s in spans)
        cols = _projection_columns(spans, rx0, rx1)
        if len(cols) < 3:
            break
        if len(band) == 1:
            if band[0].span.width > (rx1 - rx0) * 0.6 or singles >= 1:
                break
            singles += 1
        else:
            if not _distinct_columns(band, cols):
                break
            singles = 0
        run.append(band)
        j += 1
    while run and len(run[-1]) == 1:
        run.pop()
        j -= 1
    multi = [b for b in run if len(b) >= 2]
    spans = [a.span for b in run for a in b]
    if not spans:
        return None, start
    rx0, rx1 = min(s.x0 for s in spans), max(s.x1 for s in spans)
    cols = _projection_columns(spans, rx0, rx1)
    ncols = len(cols) - 1
    if len(multi) < 3 and not (len(multi) >= 2 and ncols >= 3):
        return None, start
    lengths = [len(s.text) for s in spans]
    words = [len(s.text.split()) for s in spans]
    if statistics.median(lengths) > 38 or (ncols <= 3 and statistics.median(words) >= 6):
        return None, start  # prose in columns, not a table
    # Row edges between multi-cell bands; a single-span band continues the row above.
    rows_edges = [min(a.y0 for a in run[0])]
    for prev, band in zip(run, run[1:], strict=False):
        if len(band) >= 2:
            rows_edges.append((max(a.y1 for a in prev) + min(a.y0 for a in band)) / 2)
    rows_edges.append(max(a.y1 for a in run[-1]))
    words = [w for s in spans for w in words_of(s)]
    rows = _grid_rows(words, cols, rows_edges)
    y0 = min(s.y0 for s in spans)
    y1 = max(s.y1 for s in spans)
    return _table_block((rx0, y0, rx1, y1), rows), j


def _distinct_columns(band: list[Atom], cols: list[float]) -> bool:
    seen = set()
    for a in band:
        c = _bucket((a.x0 + a.x1) / 2, cols)
        if c in seen:
            return False
        seen.add(c)
    return True


# ============================================================================= figures
def chart_regions(g: Graphics, width: float, height: float) -> list[list[float]]:
    """Vector charts: clusters of non-rule ink (data curves, bars, markers), grown to take in
    the rules drawn around them (axes, ticks, legend frame, grid)."""
    boxes = [list(b) for b in _cluster_boxes(g.ink, 6) if _area(b) > width * height * 0.01]
    rules = [(x0, y, x1, y) for y, x0, x1 in g.hrules] + [(x, y0, x, y1) for x, y0, y1 in g.vrules]
    for box in boxes:
        for _ in range(4):
            w, h = box[2] - box[0], box[3] - box[1]
            grow = [box[0] - w * 0.25, box[1] - h * 0.25, box[2] + w * 0.25, box[3] + h * 0.25]
            near = [box[0] - 6, box[1] - 6, box[2] + 6, box[3] + 6]
            changed = False
            for r in rules:
                touches = (
                    r[0] <= near[2] and r[2] >= near[0] and r[1] <= near[3] and r[3] >= near[1]
                )
                if touches and _inside(r, grow) and not _inside(r, box):
                    box[0], box[1] = min(box[0], r[0]), min(box[1], r[1])
                    box[2], box[3] = max(box[2], r[2]), max(box[3], r[3])
                    changed = True
            if not changed:
                break
    return boxes


def without_rules_in(g: Graphics, boxes: list[list[float]]) -> Graphics:
    """The same graphics minus the rules that belong to charts (so they can't form tables)."""
    if not boxes:
        return g

    def free(r) -> bool:
        return not any(_inside(r, b, 3) for b in boxes)

    return Graphics(
        hrules=[h for h in g.hrules if free((h[1], h[0], h[2], h[0]))],
        vrules=[v for v in g.vrules if free((v[0], v[1], v[0], v[2]))],
        ink=g.ink,
        images=g.images,
    )


def _label_like(s: Span) -> bool:
    """Tick values and axis titles: short, not a sentence, not a caption or list item."""
    t = s.text.strip()
    return (
        bool(t)
        and len(t) <= 30
        and len(t.split()) <= 4
        and not _CAPTION.match(t)
        and not _is_list_start(t)
        and not (t.endswith(".") and not t[:-1].replace(",", "").replace(".", "").isdigit())
    )


def detect_figures(
    g: Graphics,
    spans: list[Span],
    tables: list[Block],
    width: float,
    height: float,
    charts: list[list[float]] | None = None,
):
    """Raster images + vector charts. Labels inside (or hugging) a figure belong to it."""
    raster = [list(b) for b in g.images]
    if charts is None:
        charts = chart_regions(g, width, height)
    boxes = [list(b) for b in _cluster_boxes([tuple(b) for b in raster + charts], 2)]
    figures: list[Block] = []
    remaining = list(spans)
    for box in boxes:
        box = [max(0, box[0]), max(0, box[1]), min(width, box[2]), min(height, box[3])]
        if box[2] - box[0] < 12 or box[3] - box[1] < 12:
            continue
        if any(_inside(box, t.bbox, 3) for t in tables):
            continue
        is_raster = any(_inside(r, box, 2) and _inside(box, r, 2) for r in raster)
        inside = [s for s in remaining if _inside((s.x0, s.y0, s.x1, s.y1), box, 2)]
        words = sum(len(s.text.split()) for s in inside)
        text_area = sum(s.width * s.height for s in inside)
        prose = words > 40 or text_area > _area(box) * 0.35
        full_page = _area(box) > width * height * 0.85
        if prose and not full_page:
            # A shaded box behind a paragraph: the text stays prose; keep the art only if raster.
            if not is_raster:
                continue
            inside = []
        elif not is_raster:
            # Tick values and axis titles sit just outside the plot area: take them in
            # (twice, so an axis title outside the tick labels comes along too).
            for _ in range(2):
                for s in remaining:
                    if s in inside or not _label_like(s):
                        continue
                    m = max(s.size * 3.5, 18)
                    near = (box[0] - m, box[1] - m, box[2] + m, box[3] + m)
                    if _inside((s.x0, s.y0, s.x1, s.y1), near):
                        inside.append(s)
                        box = [
                            min(box[0], s.x0),
                            min(box[1], s.y0),
                            max(box[2], s.x1),
                            max(box[3], s.y1),
                        ]
        chars = [c for s in inside for c in s.chars]
        figures.append(Block("figure", tuple(box), text=_chars_text(chars)))
        ids = {id(s) for s in inside}
        remaining = [s for s in remaining if id(s) not in ids]
    return figures, remaining


def _area(b) -> float:
    return max(0.0, b[2] - b[0]) * max(0.0, b[3] - b[1])


def _inside(inner, outer, tol: float = 0) -> bool:
    return (
        inner[0] >= outer[0] - tol
        and inner[1] >= outer[1] - tol
        and inner[2] <= outer[2] + tol
        and inner[3] <= outer[3] + tol
    )


def _cluster_boxes(boxes, gap: float) -> list[tuple[float, float, float, float]]:
    boxes = [list(b) for b in boxes]
    changed = True
    while changed:
        changed = False
        out: list[list[float]] = []
        for b in boxes:
            for o in out:
                if (
                    b[0] <= o[2] + gap
                    and o[0] <= b[2] + gap
                    and b[1] <= o[3] + gap
                    and o[1] <= b[3] + gap
                ):
                    o[0], o[1], o[2], o[3] = (
                        min(o[0], b[0]),
                        min(o[1], b[1]),
                        max(o[2], b[2]),
                        max(o[3], b[3]),
                    )
                    changed = True
                    break
            else:
                out.append(b)
        boxes = out
    return [tuple(b) for b in boxes]


# ============================================================================= lines & paragraphs
@dataclass
class Line:
    spans: list[Span]
    x0: float = 0
    y0: float = 0
    x1: float = 0
    y1: float = 0

    def __post_init__(self) -> None:
        self.x0 = min(s.x0 for s in self.spans)
        self.y0 = min(s.y0 for s in self.spans)
        self.x1 = max(s.x1 for s in self.spans)
        self.y1 = max(s.y1 for s in self.spans)

    @property
    def text(self) -> str:
        return " ".join(s.text.strip() for s in self.spans if s.text.strip())

    @property
    def segments(self) -> list[tuple[str, str]]:
        out: list[tuple[str, str]] = []
        for i, s in enumerate(self.spans):
            if i:
                out.append(("n", " "))
            out += s.segments
        return out

    @property
    def size(self) -> float:
        return max(self.spans, key=lambda s: len(s.chars)).size

    @property
    def bold(self) -> bool:
        return all(s.bold for s in self.spans)

    @property
    def mono(self) -> bool:
        return all(s.mono for s in self.spans)

    @property
    def math(self) -> float:
        n = sum(len(s.chars) for s in self.spans)
        return sum(s.math * len(s.chars) for s in self.spans) / max(n, 1)

    @property
    def has_scripts(self) -> bool:
        return any(k != "n" for s in self.spans for k, _ in s.segments)


def _is_list_start(text: str) -> str | None:
    t = text.lstrip()
    if t[:1] in BULLETS and (len(t) == 1 or t[1:2] == " "):
        return t[0]
    m = _ENUM.match(t)
    return m.group(0) if m else None


def _formula_like(line: Line) -> bool:
    text = line.text
    compact = text.replace(" ", "")
    if not compact or len(compact) > 160 or not any(c.isalnum() for c in compact):
        return False  # "_____" signature lines, dot leaders…
    words = [w for w in re.split(r"\s+", text) if len(w) > 3 and w.isalpha()]
    if len(words) >= 5:
        return False  # prose with a symbol or two
    score = math_score(text)
    return (
        line.math >= 0.4
        or score >= 0.22
        or (line.has_scripts and score >= 0.1)
        or ("=" in text and len(words) <= 1 and any(c.isdigit() or c.isalpha() for c in compact))
    )


def _join_lines(lines: list[Line]) -> str:
    text = ""
    for ln in lines:
        t = ln.text.strip()
        if not text:
            text = t
        elif text.endswith("-") and len(text) > 1 and text[-2].isalpha() and t[:1].islower():
            text = text[:-1] + t
        else:
            text += " " + t
    return text


def lines_to_blocks(lines: list[Line], body: float) -> list[Block]:
    blocks: list[Block] = []
    group: list[Line] = []
    kind = "paragraph"

    def flush():
        nonlocal group, kind
        if not group:
            return
        x0 = min(ln.x0 for ln in group)
        y0 = min(ln.y0 for ln in group)
        x1 = max(ln.x1 for ln in group)
        y1 = max(ln.y1 for ln in group)
        size = statistics.median(ln.size for ln in group)
        bold = all(ln.bold for ln in group)
        if kind == "code":
            text = "\n".join(_indent(ln, x0, size) + ln.text for ln in group)
            b = Block("code", (x0, y0, x1, y1), text=text)
        elif kind == "formula":
            segs: list[tuple[str, str]] = []
            number = None
            for ln in group:
                spans = list(ln.spans)
                if len(spans) > 1 and _EQ_NUMBER.match(spans[-1].text.strip()):
                    number = spans.pop().text.strip()
                if segs:
                    segs.append(("n", " "))
                segs += Line(spans).segments
            b = Block(
                "formula",
                (x0, y0, x1, y1),
                text=segments_text(segs).strip(),
                latex=segments_latex(segs),
                number=number,
            )
        else:
            text = _join_lines(group)
            b = Block(kind, (x0, y0, x1, y1), text=text)
            if kind == "list_item":
                b.marker = _is_list_start(text)
                b.text = text.lstrip()[len(b.marker) :].strip() if b.marker else text
        b.font_size, b.bold, b.lines = size, bold, len(group)
        blocks.append(b)
        group = []
        kind = "paragraph"

    for ln in lines:
        text = ln.text
        if not text.strip():
            continue
        this_kind = "paragraph"
        if ln.mono and len(text) > 1:
            this_kind = "code"
        elif _formula_like(ln):
            this_kind = "formula"
        elif _is_list_start(text):
            this_kind = "list_item"
        if group:
            prev = group[-1]
            size = max(prev.size, 4)
            gap = ln.y0 - prev.y1
            overlap = min(prev.x1, ln.x1) - max(prev.x0, ln.x0)
            same_style = abs(ln.size - prev.size) <= size * 0.15 and ln.bold == prev.bold
            continues = (
                gap <= size * PARA_GAP_EM and gap > -size * 0.5 and overlap > 0 and same_style
            )
            if kind == "code":
                continues = this_kind == "code" and gap <= size * 1.2 and overlap > -size
            elif kind == "formula":
                continues = this_kind == "formula" and gap <= size * 0.9
            elif this_kind in ("list_item", "formula", "code"):
                continues = False
            elif kind == "list_item":
                # Wrapped item text is either indented under the text (hanging indent) or
                # flush with the marker — the latter only right after a full-width line.
                first = group[0]
                indent_ok = ln.x0 >= first.x0 + size * 0.3
                wrapped = ln.x0 >= first.x0 - 2 and prev.x1 >= max(g.x1 for g in group) - size * 2
                continues = continues and (indent_ok or wrapped)
            else:
                text_so_far = prev.text.rstrip()
                short_prev = prev.x1 < max(g.x1 for g in group) - size * 2.5
                if short_prev and text_so_far[-1:] in ".:!?":
                    continues = False
                if ln.x0 > prev.x0 + size * 0.9 and len(group) >= 1 and not short_prev:
                    continues = False  # first-line indent starts a new paragraph
            if not continues:
                flush()
        if not group:
            kind = this_kind
        group.append(ln)
    flush()
    return blocks


def _indent(ln: Line, x0: float, size: float) -> str:
    return " " * max(0, round((ln.x0 - x0) / max(size * 0.6, 1)))


# ============================================================================= page analysis
@dataclass
class PageResult:
    page: Page
    sizes: Counter  # char size -> count, for the document body size
    chars: int
    map_errors: int


def analyze_page(pdf: pdfium.PdfDocument, index: int, opts: LayoutOptions) -> PageResult:
    page = pdf[index]
    try:
        # Effective visible box. (get_cropbox() ignores a MediaBox inherited from /Pages
        # and silently falls back to US Letter.)
        crop = page.get_bbox()
        width, height = crop[2] - crop[0], crop[3] - crop[1]
        chars, rotated, fonts, map_errors = read_chars(page, crop)
        g = read_graphics(page, crop, width, height)
        spans = build_spans(chars, fonts) if chars else []
        rot_spans = [Span(grp, fonts) for grp in _group_rotated(rotated)]
        sizes: Counter = Counter(round(c.size * 2) / 2 for c in chars)
        body = sizes.most_common(1)[0][0] if sizes else 10.0

        # Charts first: their axes, ticks and legend frame are rules too, and must not be
        # mistaken for a table grid.
        charts = chart_regions(g, width, height)
        tables: list[Block] = []
        if opts.detect_tables:
            tables, spans = detect_ruled_tables(spans, without_rules_in(g, charts))
        figures, spans = detect_figures(g, spans + rot_spans, tables, width, height, charts)

        atoms = [Atom("span", s.x0, s.y0, s.x1, s.y1, span=s) for s in spans]
        atoms += [Atom(b.type, *b.bbox, block=b) for b in tables + figures]
        bands = reading_order(atoms, max(GUTTER_MIN, body * 0.8))

        blocks: list[Block] = []
        pending: list[Line] = []
        i = 0
        while i < len(bands):
            band = bands[i]
            if len(band) == 1 and band[0].kind != "span":
                blocks += lines_to_blocks(pending, body)
                pending = []
                blocks.append(band[0].block)
                i += 1
                continue
            if opts.detect_tables and len(band) >= 2:
                table, j = unruled_table(bands, i, body)
                if table is not None:
                    blocks += lines_to_blocks(pending, body)
                    pending = []
                    blocks.append(table)
                    i = j
                    continue
            spans_in = [a.span for a in band if a.span]
            for a in band:
                if a.kind != "span":
                    blocks += lines_to_blocks(pending, body)
                    pending = []
                    blocks.append(a.block)
            if spans_in:
                pending.append(Line(spans_in))
            i += 1
        blocks += lines_to_blocks(pending, body)
        if not opts.detect_formulas:
            for b in blocks:
                if b.type == "formula":
                    b.type = "paragraph"

        result = Page(index + 1, width, height, blocks)
        result.scanned = not chars and any(_area(b) > width * height * 0.5 for b in g.images)
        if opts.images:
            _attach_images(page, result, opts)
        return PageResult(result, sizes, len(chars), map_errors)
    finally:
        page.close()


def _group_rotated(chars: list[Char]) -> list[list[Char]]:
    groups: list[list[Char]] = []
    for ch in chars:
        if groups:
            last = groups[-1][-1]
            if abs(ch.cx - last.cx) < ch.size * 2 and abs(ch.cy - last.cy) < ch.size * 2:
                groups[-1].append(ch)
                continue
        groups.append([ch])
    return groups


def _attach_images(page: pdfium.PdfPage, result: Page, opts: LayoutOptions) -> None:
    wanted = {"figure"}
    if opts.table_images:
        wanted.add("table")
    if opts.formula_images:
        wanted.add("formula")
    targets = [b for b in result.blocks if b.type in wanted and b.bbox]
    if not targets:
        return
    scale = opts.image_scale
    W, H = result.width, result.height
    counters: Counter = Counter()
    for b in targets:
        pad = 3
        x0, y0 = max(0.0, b.bbox[0] - pad), max(0.0, b.bbox[1] - pad)
        x1, y1 = min(W, b.bbox[2] + pad), min(H, b.bbox[3] + pad)
        if (x1 - x0) * scale < 4 or (y1 - y0) * scale < 4:
            continue
        # Render only this region: crop = what to cut from (left, bottom, right, top).
        bitmap = page.render(scale=scale, rotation=0, crop=(x0, H - y1, W - x1, y0))
        img = bitmap.to_pil()
        bitmap.close()
        buf = io.BytesIO()
        img.save(buf, format="PNG", compress_level=6)
        counters[b.type] += 1
        name = f"p{result.number}-{b.type}-{counters[b.type]}.png"
        b.image = ImageData(name, "image/png", img.width, img.height, buf.getvalue())


def analyze_pages(
    source, password: str | None, indices: list[int], opts: LayoutOptions
) -> list[PageResult]:
    """Top-level (picklable) entry point: analyse some pages of a document."""
    pdf = pdfium.PdfDocument(source, password=password)
    try:
        return [analyze_page(pdf, i, opts) for i in indices]
    finally:
        pdf.close()


# ============================================================================= document passes
def _signature(text: str) -> str:
    return re.sub(r"\d+", "#", " ".join(strip_accents_lower(text).split()))


def finalize(results: list[PageResult], heading_hints: dict[str, int] | None = None) -> list[Page]:
    pages = [r.page for r in results]
    total: Counter = Counter()
    for r in results:
        total.update(r.sizes)
    body = total.most_common(1)[0][0] if total else 10.0

    _mark_furniture(pages)
    _classify_headings(pages, body, heading_hints or {})
    for p in pages:
        _link_captions(p)
        for n, b in enumerate(p.blocks):
            b.order = n
            b.id = f"p{p.number}-b{n}"
    return pages


def _furniture_key(b: Block) -> str:
    if b.type == "figure":  # a logo repeated on every page: same place, same size
        x0, y0, x1, y1 = b.bbox
        return f"fig:{round(x0 / 6)},{round(y0 / 6)},{round((x1 - x0) / 6)},{round((y1 - y0) / 6)}"
    return _signature(b.text)


def _mark_furniture(pages: list[Page]) -> None:
    def zone(b: Block, p: Page) -> str | None:
        if b.bbox is None or b.type not in ("paragraph", "heading", "list_item", "figure"):
            return None
        if b.bbox[3] <= p.height * EDGE_ZONE + 20 or (
            b.type == "figure" and b.bbox[1] <= p.height * EDGE_ZONE
        ):
            return "header"
        if b.bbox[1] >= p.height * (1 - EDGE_ZONE) - 20:
            return "footer"
        return None

    counts: Counter = Counter()
    for p in pages:
        counts.update({(zone(b, p), _furniture_key(b)) for b in p.blocks if zone(b, p)})
    need = max(2, math.ceil(len(pages) * 0.5))
    for p in pages:
        for b in p.blocks:
            z = zone(b, p)
            if not z:
                continue
            key = _furniture_key(b)
            if b.type != "figure" and _PAGE_NUMBER.fullmatch(b.text.strip()):
                b.type = "page_number"
            elif len(pages) >= 2 and counts[(z, key)] >= need and len(key) >= 3:
                b.type = z


def _classify_headings(pages: list[Page], body: float, hints: dict[str, int]) -> None:
    candidates: list[tuple[Block, str]] = []
    for p in pages:
        blocks = p.blocks
        for i, b in enumerate(blocks):
            if b.type != "paragraph" or not b.text:
                continue
            text = b.text.strip()
            key = _signature(text)
            if key in hints:
                b.type, b.level = "heading", hints[key]
                continue
            if b.lines > 3 or len(text) > 200 or text[-1:] in ",;" or _CAPTION.match(text):
                continue
            size = b.font_size or body
            nxt = next((x for x in blocks[i + 1 :] if x.type not in FURNITURE), None)
            letters = [c for c in text if c.isalpha()]
            caps = len(letters) >= 4 and all(c.isupper() for c in letters) and len(text) <= 90
            key_value = bool(_KEY_VALUE.match(text))  # "Centro de Custo: 88.530" is a field
            if size >= body * 1.18 and not key_value:
                candidates.append((b, "size"))
            elif key_value:
                continue
            elif (b.bold and len(text) <= 140 and b.lines <= 2 and text[-1:] != "."
                  and (nxt is None or not nxt.bold or nxt.type != "paragraph")):  # fmt: skip
                candidates.append((b, "bold"))
            elif caps and b.lines == 1 and text[-1:] != ".":
                candidates.append((b, "caps"))
    size_levels = sorted(
        {round((b.font_size or body) * 2) / 2 for b, why in candidates if why == "size"},
        reverse=True,
    )
    size_levels = size_levels[:3]
    top = len(size_levels)
    for b, why in candidates:
        b.type = "heading"
        m = _NUMBERED_HEADING.match(b.text)
        if why == "size":
            key = round((b.font_size or body) * 2) / 2
            b.level = size_levels.index(key) + 1 if key in size_levels else top
        else:
            b.level = min(6, top + 1)
        if m and why != "size":
            b.level = min(6, max(b.level, m.group(1).count(".") + 1 + (1 if top else 0)))


def _link_captions(page: Page) -> None:
    targets = [b for b in page.blocks if b.type in ("figure", "table") and b.bbox]
    for b in page.blocks:
        if (
            b.type not in ("paragraph", "heading")
            or not b.bbox
            or not _CAPTION.match(b.text.strip())
        ):
            continue
        if len(b.text) > 400:
            continue
        best, dist = None, math.inf
        for t in targets:
            overlap = min(b.bbox[2], t.bbox[2]) - max(b.bbox[0], t.bbox[0])
            if overlap <= 0:
                continue
            d = min(abs(b.bbox[1] - t.bbox[3]), abs(t.bbox[1] - b.bbox[3]))
            if d < dist:
                best, dist = t, d
        if best is not None and dist <= 60:
            b.type = "caption"
            b.level = None
            if best.caption is None:
                best.caption = b.text
        elif b.lines <= 3 and _STRICT_CAPTION.match(b.text.strip()):
            b.type = "caption"
            b.level = None
